spring.application.name=filterbot

# Telegram
telegram.api.id=${TELEGRAM_API_ID}
telegram.api.hash=${TELEGRAM_API_HASH}
botapi=${BOT_API}
bot.username=${BOT_USERNAME}
bot.allowed.chat.ids=${BOT_ALLOWED_CHAT_IDS}

# Google APIs
gemini.api.key=${GEMINI_API_KEY}
google.sheets.credentials=classpath:google-credentials.json
google.sheets.spreadsheet.id=${GOOGLE_SHEETS_SPREADSHEET_ID}

# External APIs
polymarkets.api.URL=https://gamma-api.polymarket.com

# Logging
logging.level.it.tdlight.TDLight=WARN
